# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TMDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TMDB
  pod 'SnapKit'

  target 'TMDBTests' do
    inherit! :complete
    # Pods for testing
    pod 'Nimble', '~> 8.0.0'
    pod 'Quick', '~> 2.1.0'
  end
  
end
